export const demoData = [
  {
    char_id: 7,
    name: "Mike Ehrmantraut",
    birthday: "Unknown",
    occupation: ["Hitman", "Private Investigator", "Ex-Cop"],
    img: "https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_mike-ehrmantraut-lg.jpg",
    status: "Deceased",
    nickname: "Mike",
    appearance: [2, 3, 4, 5],
    portrayed: "Jonathan Banks",
    category: "Breaking Bad, Better Call Saul",
    better_call_saul_appearance: [1, 2, 3, 4, 5],
    filter: [
      {
        id: 0,
        name: "Saturation",
        property: "saturate",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 1,
        name: "Blur",
        property: "blur",
        value: 0,
        range: { min: 0, max: 20 },
        unit: "px",
      },
      {
        id: 2,
        name: "Brightness",
        property: "brightness",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 3,
        name: "Contrast",
        property: "contrast",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
    ],
  },
  {
    char_id: 2,
    name: "Jesse Pinkman",
    birthday: "09-24-1984",
    occupation: ["Meth Dealer"],
    img: "https://vignette.wikia.nocookie.net/breakingbad/images/9/95/JesseS5.jpg/revision/latest?cb=20120620012441",
    status: "Alive",
    nickname: "Cap n' Cook",
    appearance: [1, 2, 3, 4, 5],
    portrayed: "Aaron Paul",
    category: "Breaking Bad",
    better_call_saul_appearance: [],
    filter: [
      {
        id: 0,
        name: "Saturation",
        property: "saturate",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 1,
        name: "Blur",
        property: "blur",
        value: 0,
        range: { min: 0, max: 20 },
        unit: "px",
      },
      {
        id: 2,
        name: "Brightness",
        property: "brightness",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 3,
        name: "Contrast",
        property: "contrast",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
    ],
  },
  {
    char_id: 8,
    name: "Saul Goodman",
    birthday: "Unknown",
    occupation: ["Lawyer"],
    img: "https://vignette.wikia.nocookie.net/breakingbad/images/1/16/Saul_Goodman.jpg/revision/latest?cb=20120704065846",
    status: "Alive",
    nickname: "Jimmy McGill",
    appearance: [2, 3, 4, 5],
    portrayed: "Bob Odenkirk",
    category: "Breaking Bad, Better Call Saul",
    better_call_saul_appearance: [1, 2, 3, 4, 5],
    filter: [
      {
        id: 0,
        name: "Saturation",
        property: "saturate",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 1,
        name: "Blur",
        property: "blur",
        value: 0,
        range: { min: 0, max: 20 },
        unit: "px",
      },
      {
        id: 2,
        name: "Brightness",
        property: "brightness",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 3,
        name: "Contrast",
        property: "contrast",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
    ],
  },
  {
    char_id: 1,
    name: "Walter White",
    birthday: "09-07-1958",
    occupation: ["High School Chemistry Teacher", "Meth King Pin"],
    img: "https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_walter-white-lg.jpg",
    status: "Presumed dead",
    nickname: "Heisenberg",
    appearance: [1, 2, 3, 4, 5],
    portrayed: "Bryan Cranston",
    category: "Breaking Bad",
    better_call_saul_appearance: [],
    filter: [
      {
        id: 0,
        name: "Saturation",
        property: "saturate",
        value: "187",
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 1,
        name: "Blur",
        property: "blur",
        value: "0",
        range: { min: 0, max: 20 },
        unit: "px",
      },
      {
        id: 2,
        name: "Brightness",
        property: "brightness",
        value: "128",
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 3,
        name: "Contrast",
        property: "contrast",
        value: "200",
        range: { min: 0, max: 200 },
        unit: "%",
      },
    ],
  },
  {
    char_id: 3,
    name: "Skyler White",
    birthday: "08-11-1970",
    occupation: [
      "House wife",
      "Book Keeper",
      "Car Wash Manager",
      "Taxi Dispatcher",
    ],
    img: "https://s-i.huffpost.com/gen/1317262/images/o-ANNA-GUNN-facebook.jpg",
    status: "Alive",
    nickname: "Sky",
    appearance: [1, 2, 3, 4, 5],
    portrayed: "Anna Gunn",
    category: "Breaking Bad",
    better_call_saul_appearance: [],
    filter: [
      {
        id: 0,
        name: "Saturation",
        property: "saturate",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 1,
        name: "Blur",
        property: "blur",
        value: 0,
        range: { min: 0, max: 20 },
        unit: "px",
      },
      {
        id: 2,
        name: "Brightness",
        property: "brightness",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 3,
        name: "Contrast",
        property: "contrast",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
    ],
  },
  {
    char_id: 6,
    name: "Marie Schrader",
    birthday: "Unknown",
    occupation: ["Housewife", "Clepto"],
    img: "https://vignette.wikia.nocookie.net/breakingbad/images/1/10/Season_2_-_Marie.jpg/revision/latest?cb=20120617211645",
    status: "Alive",
    nickname: "Marie",
    appearance: [1, 2, 3, 4, 5],
    portrayed: "Betsy Brandt",
    category: "Breaking Bad",
    better_call_saul_appearance: [],
    filter: [
      {
        id: 0,
        name: "Saturation",
        property: "saturate",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 1,
        name: "Blur",
        property: "blur",
        value: 0,
        range: { min: 0, max: 20 },
        unit: "px",
      },
      {
        id: 2,
        name: "Brightness",
        property: "brightness",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
      {
        id: 3,
        name: "Contrast",
        property: "contrast",
        value: 100,
        range: { min: 0, max: 200 },
        unit: "%",
      },
    ],
  },
];
